### ISSUE TITLE
Incompatible Update from older version.

### ISSUE THREAD

**Issue by StoneLegion** [Piepenguin1995/rfwindmill#20]
I was looking forward to the update but you seem to have removed all the old windmills in the world during the update. As you can see from this picture this is what survived from tier 1-4:
http://i.imgur.com/XfIgfxC.png

Funny thing both you and SolarFlux had butchered their blocks during updates hehe:
http://i.imgur.com/hKT7NDS.png 

But they actually fixed it so they some how get updated when I had reported it maybe you can do it too as you can see their solar panels still showed up:
http://i.imgur.com/2hsHOO4.png

I hope there is some how you can look into patching it so we can not lose our Windmills. We have many dozens if not 100's scattered around the world with over 50+ Players so we can't keep track of them.

**Comment by EmilyMansfield** [comment]
Yeah I mentioned the incompatibility in the release notes, sorry about that. Basic windmills should have been preserved, but I swapped from making them all separate blocks (which was necessary originally) into a single block with metadata.
I'll look into some kind of automated conversion to the new version for you, NBT-wise they're identical between versions so only the block ids and metadata need to be changed in the world files. I'll see what I can do.

**Comment by StoneLegion** [comment]
Thank you I did check out the notes I did want to see if it was possible still. Hoping there is a easy way thanks again!

**Comment by EmilyMansfield** [comment]
Apparently MCEdit can do the block replacement as can [this program](http://www.planetminecraft.com/mod/kirby0016s-blockreplacer/). If you do use those or something similar then either get the IDs from NEI, say 200, 201, 202, 203 for simplicity. Then you need to map 200 -> 200:0, 201 -> 200:1, 202 -> 200:2, 203 -> 200:3. That should work since its reducing block ids not gaining them. Then upgrade to the new mod and hopefully the mode will work. Alternatively if the program wants the names then forge told you what those were, i.e. rfwindmill:WindmillBlock2 -> rfwindmill:WindmillBlock1 with metadata 1 (metadata starts from 0 whereas the names start from 1).

I'll look into SolarFlux's code too and see what change they made, if it doesn't involve keeping the old blocks I'll see if I can integrate it, but the above should work.

**Comment by EmilyMansfield** [comment]
Sorry, their fix isn't applicable to this situation, it appears SolarFlux broke due to a decrement in id for the blocks, whereas this incompatibility is caused by deleting three of the block types outright. I'll see if I can come up with a more robust solution than what I just posted, but I can't guarantee anything I'm afraid!

**Comment by StoneLegion** [comment]
Thanks for trying. If there is no solution there is no solution. Will try to do some sort of reimbursement program and hope everyone is honorable about it.

**Comment by EmilyMansfield** [comment]
Sorry I can't be of more help, and I apologise for breaking your server! (The update isn't completely necessary though, it only adds the upgrade recipes and the textures, and you can mod the old jar file with the new textures easily enough if you want to). Hopefully your players will take it well.
